



--SELECT  top 1000 PATIENT.PAT_MRN_ID, PAT_ENC.[PAT_ID], PAT_ENC.[PAT_ENC_CSN_ID], 
--  PATIENT_FYI_FLAGS.NOTE_ID, PATIENT_FYI_FLAGS.PAT_FLAG_TYPE_C, 
--  --PATIENT_FYI_FLAGS.PAT_FLAG_EXP_DATE,
--   PATIENT_FYI_FLAGS.ACTIVE_C, ZC_ACTIVE.Name as ActiveFlag,
--  ZC_BPA_TRIGGER_FYI.NAME as TriggerName 
--       ,[ACCT_NOTE_INSTANT]
--      ,[LAST_UPDATE_INST]
Select top 100 *

  FROM [CLARITY].[dbo].[PATIENT_FYI_FLAGS] with (nolock)
  INNER JOIN [CLARITY].[dbo].[PATIENT] PATIENT with (nolock) ON PAT_ID =  PATIENT.PAT_ID
  --INNER JOIN [CLARITY].[dbo].[PATIENT_FYI_FLAGS] PATIENT_FYI_FLAGS with (nolock)  On PAT_ENC.PAT_ID = PATIENT_FYI_FLAGS.PATIENT_ID AND PAT_ENC.PAT_ENC_CSN_ID = PATIENT_FYI_FLAGS.PAT_ENC_CSN_ID
  --INNER JOIN [CLARITY].[dbo].[ZC_ACTIVE] ZC_ACTIVE with (nolock)   on PATIENT_FYI_FLAGS.ACTIVE_C =  ZC_ACTIVE.ACTIVE_C

Where PAT_FLAG_TYPE_C IN (2012,2027,2028)
and ACTIVE_C = 1


  --Where ZC_BPA_TRIGGER_FYI.INTERNAL_ID IN (Select INTERNAL_ID from [CLARITY].[dbo].[ZC_BPA_TRIGGER_FYI] Where Name like '%Pharm%')

--PatientEpicId

--Select * from [CLARITY].[dbo].[ZC_BPA_TRIGGER_FYI] Where Name like '%Pharm%'

--Select * from [CLARITY].[dbo].[PATIENT_FYI_FLAGS] Where PAT_FLAG_TYPE_C IN (2012,2025,2026,2027)

--2026 = retail
--2012,2025,2027 = special
