SELECT 
    PAT_ID, 
    PAT_FLAG_TYPE_C, 
    ACCT_NOTE_INSTANT AS FlagDate,
    CASE 
        WHEN PAT_FLAG_TYPE_C = 2026 THEN 'Retail'
        WHEN PAT_FLAG_TYPE_C IN (2012, 2025, 2027) THEN 'Special'
        ELSE NULL
    END AS test
FROM (
    SELECT 
        PAT_ID,
        PAT_FLAG_TYPE_C,
        ACCT_NOTE_INSTANT,
        ROW_NUMBER() OVER (PARTITION BY pat.PAT_ID ORDER BY ACCT_NOTE_INSTANT DESC) AS rn
    FROM [CLARITY].[dbo].[PATIENT] AS pat WITH (NOLOCK)
    INNER JOIN [CLARITY].[dbo].[PATIENT_FYI_FLAGS] WITH (NOLOCK) ON pat.PAT_ID = PAT_ID
    WHERE PAT_FLAG_TYPE_C IN (2012,2025,2026,2027)
      AND ACTIVE_C = 1
) t
WHERE rn = 1
