USE [AetnaClaims_DEV]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[staging].[MemberRetailPharmacyClaims]') AND type in (N'U'))
DROP TABLE [staging].[MemberRetailPharmacyClaims]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [staging].[MemberRetailPharmacyClaims](
	[ps_unique_id] [varchar](MAX) NULL,
	[customer_nbr] [varchar](MAX) NULL,
	[group_nbr] [varchar](MAX) NULL,
	[file_source] [varchar](MAX) NULL,
	[subgroup_nbr] [varchar](MAX) NULL,
	[account_nbr] [varchar](MAX) NULL,
	[lob] [varchar](MAX) NULL,
	[rx_product_cd] [varchar](MAX) NULL,
	[plan_id] [varchar](MAX) NULL,
	[fund_ctg_cd] [varchar](MAX) NULL,
	[benefit_tier] [varchar](MAX) NULL,
	[rx_intgrtn_opt_cd] [varchar](MAX) NULL,
	[ee_id] [varchar](MAX) NULL,
	[ee_last_name] [varchar](MAX) NULL,
	[ee_first_name] [varchar](MAX) NULL,
	[subs_zip_cd] [varchar](MAX) NULL,
	[ssn_nbr] [varchar](MAX) NULL,
	[member_id] [varchar](MAX) NULL,
	[src_rx_member_id] [varchar](MAX) NULL,
	[src_last_name] [varchar](MAX) NULL,
	[src_first_name] [varchar](MAX) NULL,
	[src_mbr_gender_cd] [varchar](MAX) NULL,
	[mbr_rtp_type_cd] [varchar](MAX) NULL,
	[src_mbr_birth_dt] [varchar](MAX) NULL,
	[filler1] [varchar](MAX) NULL,
	[filler2] [varchar](MAX) NULL,
	[clm_status] [varchar](MAX) NULL,
	[dir_mbr_reim_ind] [varchar](MAX) NULL,
	[ee_ntwk_srv_area_id] [varchar](MAX) NULL,
	[office_id] [varchar](MAX) NULL,
	[sort_name] [varchar](MAX) NULL,
	[prescriber_id] [varchar](MAX) NULL,
	[spclty_ctg_cd] [varchar](MAX) NULL,
	[address_line_1] [varchar](MAX) NULL,
	[address_line_2] [varchar](MAX) NULL,
	[nabp_nbr] [varchar](MAX) NULL,
	[phm_zip_cd] [varchar](MAX) NULL,
	[process_dt] [varchar](MAX) NULL,
	[disp_dt] [varchar](MAX) NULL,
	[ndc_cd] [varchar](MAX) NULL,
	[label_nm] [varchar](MAX) NULL,
	[formulary_cd] [varchar](MAX) NULL,
	[generic_cd] [varchar](MAX) NULL,
	[source_type_cd] [varchar](MAX) NULL,
	[retail_mod_cd] [varchar](MAX) NULL,
	[new_refill_cnt] [varchar](MAX) NULL,
	[daw_cd] [varchar](MAX) NULL,
	[unts_dispensed_qty] [varchar](MAX) NULL,
	[days_supply_cnt] [varchar](MAX) NULL,
	[sub_ing_cost_amt] [varchar](MAX) NULL,
	[prof_fee_amt] [varchar](MAX) NULL,
	[awp_amt] [varchar](MAX) NULL,
	[sales_tax_amt] [varchar](MAX) NULL,
	[app_to_per_ded_amt] [varchar](MAX) NULL,
	[srv_copay_amt] [varchar](MAX) NULL,
	[paid_amt] [varchar](MAX) NULL,
	[ahf_paid_amt] [varchar](MAX) NULL,
	[ahf_bfd_amt] [varchar](MAX) NULL,
	[GPI] [varchar](MAX) NULL,
	[phi_acas_bypass_cd] [varchar](MAX) NULL,
	[price_type_cd] [varchar](MAX) NULL,
	[calc_ing_cost_amt] [varchar](MAX) NULL,
	[prescbr_id_qlfy_cd] [varchar](MAX) NULL,
	[prod_distnctn_cd] [varchar](MAX) NULL,
	[rx_claim_id] [varchar](MAX) NULL,
	[compound_cd] [varchar](MAX) NULL,
	[maint_drug_cd] [varchar](MAX) NULL,
	[prescription_nbr] [varchar](MAX) NULL,
	[NABP_Provider_Name] [varchar](MAX) NULL,
	[prescribing_prov_name] [varchar](MAX) NULL,
	[record_status] [varchar](MAX) NULL,
	[ORG_CD] [varchar](MAX) NULL,
	[EOF] [varchar](MAX) NULL,
	[Created_Date] [datetime] NULL,
	[Created_By] nvarchar(MAX) NULL,
	[Updated_Date] [datetime] NULL,
	[Updated_By] nvarchar(MAX) NULL
) ON [PRIMARY]
GO
