USE [AetnaClaims]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[staging].[MemberEligibility]') AND type in (N'U'))
DROP TABLE [staging].[MemberEligibility]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [staging].[MemberEligibility](
	[member_id] [varchar](MAX) NOT NULL,
	[eff_mm] [varchar](MAX) NOT NULL,
	[msk_prefix_nm] [varchar](MAX) NULL,
	[last_nm] [varchar](MAX) NULL,
	[first_nm] [varchar](MAX) NULL,
	[suffix_nm] [varchar](MAX) NULL,
	[mbr_gender_cd] [varchar](MAX) NULL,
	[birth_dt] [varchar](MAX) NULL,
	[address_line_1_txt] [varchar](MAX) NULL,
	[address_line_2_txt] [varchar](MAX) NULL,
	[city_nm] [varchar](MAX) NULL,
	[state_postal_cd] [varchar](MAX) NULL,
	[county_cd] [varchar](MAX) NULL,
	[zip_cd] [varchar](MAX) NULL,
	[phone_number] [varchar](MAX) NULL,
	[src_member_id] [varchar](MAX) NULL,
	[mbr_rtp_type_cd] [varchar](MAX) NULL,
	[ssn_nbr] [varchar](MAX) NULL,
	[ps_unique_id] [varchar](MAX) NULL,
	[customer_nbr] [varchar](MAX) NULL,
	[group_nbr] [varchar](MAX) NULL,
	[subgroup_nbr] [varchar](MAX) NULL,
	[account_nbr] [varchar](MAX) NULL,
	[last_nm2] [varchar](MAX) NULL,
	[first_nm2] [varchar](MAX) NULL,
	[gender_cd] [varchar](MAX) NULL,
	[subscriber_brth_dt] [varchar](MAX) NULL,
	[subs_zip_cd] [varchar](MAX) NULL,
	[subs_st_postal_cd] [varchar](MAX) NULL,
	[county_cd2] [varchar](MAX) NULL,
	[SSN_NBR2] [varchar](MAX) NULL,
	[file_id] [varchar](MAX) NULL,
	[plsp_prod_cd] [varchar](MAX) NULL,
	[product_ln_cd] [varchar](MAX) NULL,
	[fund_ctg_cd] [varchar](MAX) NULL,
	[coverage_type_cd] [varchar](MAX) NULL,
	[ntwk_srv_area_id] [varchar](MAX) NULL,
	[cust_subseg_cd] [varchar](MAX) NULL,
	[medical_ind] [varchar](MAX) NULL,
	[drug_ind] [varchar](MAX) NULL,
	[sbstnc_abuse_ind] [varchar](MAX) NULL,
	[mental_health_ind] [varchar](MAX) NULL,
	[orig_covg_eff_dt] [varchar](MAX) NULL,
	[tax_id_nbr] [varchar](MAX) NULL,
	[pcp_prvdr_id] [varchar](MAX) NULL,
	[print_nm] [varchar](MAX) NULL,
	[address_line_1_txt2] [varchar](MAX) NULL,
	[address_line_2_txt2] [varchar](MAX) NULL,
	[city_nm2] [varchar](MAX) NULL,
	[state_postal_cd2] [varchar](MAX) NULL,
	[zip_cd2] [varchar](MAX) NULL,
	[npi_nbr] [varchar](MAX) NULL,
	[SPECIALTY_CTG_CD] [varchar](MAX) NULL,
	[org_id] [varchar](MAX) NULL,
	[first_vst_dt] [varchar](MAX) NULL,
	[last_vst_dt] [varchar](MAX) NULL,
	[visit_nbr] [varchar](MAX) NULL,
	[tax_id_nbr2] [varchar](MAX) NULL,
	[attr_prvdr_id] [varchar](MAX) NULL,
	[print_nm2] [varchar](MAX) NULL,
	[address_line_1_txt3] [varchar](MAX) NULL,
	[address_line_2_txt3] [varchar](MAX) NULL,
	[city_nm3] [varchar](MAX) NULL,
	[state_postal_cd3] [varchar](MAX) NULL,
	[zip_cd3] [varchar](MAX) NULL,
	[npi_nbr2] [varchar](MAX) NULL,
	[SPECIALTY_CTG_CD2] [varchar](MAX) NULL,
	[STATUS_IND] [varchar](MAX) NULL,
	[eff_dt] [varchar](MAX) NULL,
	[cncl_dt] [varchar](MAX) NULL,
	[SRC_CUMB_ID] [varchar](MAX) NULL,
	[SRC_CUMB_ID2] [varchar](MAX) NULL,
	[middle_nm] [varchar](MAX) NULL,
	[individual_id] [varchar](MAX) NULL,
	[pulse_fsi_score] [varchar](MAX) NULL,
	[ERG_Prospective_Score] [varchar](MAX) NULL,
	[ERG_Retro_Score] [varchar](MAX) NULL,
	[product_ln_cd2] [varchar](MAX) NULL,
	[aetna_card_number] [varchar](MAX) NULL,
	[grp_cntl_name] [varchar](MAX) NULL,
	[currect_record_indicator] [varchar](MAX) NULL,
	[cumb_id_seq_no] [varchar](MAX) NULL,
	[filler] [varchar](MAX) NULL,
	[derived] [varchar](MAX) NULL,
	[attprv_USE_SOURCE] [varchar](MAX) NULL,
	[ia_fncl_risk_cd] [varchar](MAX) NULL,
	[ORG_ID2] [varchar](MAX) NULL,
	[PLAN_ID] [varchar](MAX) NULL,
	[EOF] [varchar](MAX) NULL,
	[Created_Date] [datetime] NULL,
	[Created_By] nvarchar(MAX) NULL,
	[Updated_Date] [datetime] NULL,
	[Updated_By] nvarchar(MAX) NULL
) ON [PRIMARY]
GO
