USE [AetnaClaims]
GO

/****** Object:  Table [fact].[MemberClaims]    Script Date: 9/9/2025 6:14:26 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[fact].[MemberClaims]') AND type in (N'U'))
DROP TABLE [fact].[MemberClaims]
GO

/****** Object:  Table [fact].[MemberClaims]    Script Date: 9/9/2025 6:14:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [fact].[MemberClaims](
	[member_id] [varchar](255) NULL,
	[ps_unique_id] [varchar](255) NULL,
	[customer_nbr] [varchar](255) NULL,
	[group_nbr] [varchar](255) NULL,
	[idn_ind] [varchar](255) NULL,
	[subgroup_nbr] [varchar](255) NULL,
	[account_nbr] [varchar](255) NULL,
	[file_id] [varchar](255) NULL,
	[emp_first_nm] [varchar](255) NULL,
	[emp_last_nm] [varchar](255) NULL,
	[emp_gender] [varchar](255) NULL,
	[subscriber_brth_dt] [varchar](255) NULL,
	[subs_st_postal_cd] [varchar](255) NULL,
	[subs_zip_cd] [varchar](255) NULL,
	[mem_first_nm] [varchar](255) NULL,
	[mem_last_nm] [varchar](255) NULL,
	[mem_gender] [varchar](255) NULL,
	[clm_ln_type_cd] [varchar](255) NULL,
	[non_prfrrd_srv_cd] [varchar](255) NULL,
	[plsp_prod_cd] [varchar](255) NULL,
	[product_ln_cd] [varchar](255) NULL,
	[classification_cd] [varchar](255) NULL,
	[bnft_pkg_id] [varchar](255) NULL,
	[plan_id] [varchar](255) NULL,
	[non_prfrrd_srv_cd_BEN_TIER] [varchar](255) NULL,
	[fund_ctg_cd] [varchar](255) NULL,
	[src_clm_id] [varchar](255) NULL,
	[src_claim_line_id] [varchar](255) NULL,
	[src_subscriber_id] [varchar](255) NULL,
	[srv_prvdr_id] [varchar](255) NULL,
	[srv_prvdr_npi] [varchar](255) NULL,
	[print_nm_SERVICE] [varchar](255) NULL,
	[address_line_1_txt] [varchar](255) NULL,
	[address_line_2_txt] [varchar](255) NULL,
	[city_nm] [varchar](255) NULL,
	[zip_cd] [varchar](255) NULL,
	[state_postal_cd] [varchar](255) NULL,
	[provider_type_cd] [varchar](255) NULL,
	[specialty_cd] [varchar](255) NULL,
	[prev_clm_seg_id] [varchar](255) NULL,
	[derived_tcn_nbr] [varchar](255) NULL,
	[src_claim_line_id_PAY] [varchar](255) NULL,
	[claim_line_id] [numeric](18, 0) NULL,
	[ntwk_srv_area_id] [varchar](255) NULL,
	[paid_prvdr_nsa_id] [varchar](255) NULL,
	[srv_capacity_cd] [varchar](255) NULL,
	[tax_id_format_cd_PCP] [varchar](255) NULL,
	[tax_id_nbr_PCP] [varchar](255) NULL,
	[print_nm_PCP] [varchar](255) NULL,
	[tax_id_format_cd_SERVICE] [varchar](255) NULL,
	[tax_id_nbr_SERVICE] [varchar](255) NULL,
	[payee_cd] [varchar](255) NULL,
	[paid_prvdr_par_cd] [varchar](255) NULL,
	[received_dt] [varchar](255) NULL,
	[adjn_dt] [varchar](255) NULL,
	[srv_start_dt] [varchar](255) NULL,
	[srv_stop_dt] [varchar](255) NULL,
	[paid_dt] [varchar](255) NULL,
	[mdc_cd] [varchar](255) NULL,
	[drg_cd] [varchar](255) NULL,
	[prcdr_cd] [varchar](255) NULL,
	[prcdr_modifier_cd_1] [varchar](255) NULL,
	[prcdr_type_cd_2] [varchar](255) NULL,
	[ICD10_ind] [varchar](255) NULL,
	[MED_COST_SUBCTG_CD] [varchar](255) NULL,
	[prcdr_group_nbr] [varchar](255) NULL,
	[type_srv_cd] [varchar](255) NULL,
	[srv_benefit_cd] [varchar](255) NULL,
	[tooth_1_nbr] [varchar](255) NULL,
	[plc_srv_cd] [varchar](255) NULL,
	[dschrg_status_cd] [varchar](255) NULL,
	[revenue_cd] [varchar](255) NULL,
	[hcfa_bill_type_cd] [varchar](255) NULL,
	[unit_cnt] [numeric](24, 6) NULL,
	[src_unit_cnt] [numeric](24, 6) NULL,
	[src_billed_amt] [numeric](24, 6) NULL,
	[billed_amt] [numeric](24, 6) NULL,
	[not_covered_amt_1] [numeric](24, 6) NULL,
	[not_covered_amt_2] [numeric](24, 6) NULL,
	[not_covered_amt_3] [numeric](24, 6) NULL,
	[clm_ln_msg_cd_1] [varchar](255) NULL,
	[clm_ln_msg_cd_2] [varchar](255) NULL,
	[clm_ln_msg_cd_3] [varchar](255) NULL,
	[covered_amt] [numeric](24, 6) NULL,
	[allowed_amt] [numeric](24, 6) NULL,
	[column93] [varchar](255) NULL,
	[srv_copay_amt] [numeric](24, 6) NULL,
	[src_srv_copay_amt] [numeric](24, 6) NULL,
	[deductible_amt] [numeric](24, 6) NULL,
	[coinsurance_amt] [numeric](24, 6) NULL,
	[src_coins_amt] [numeric](24, 6) NULL,
	[bnft_payable_amt] [numeric](24, 6) NULL,
	[paid_amt] [numeric](24, 6) NULL,
	[cob_paid_amt] [numeric](24, 6) NULL,
	[ahf_bfd_amt] [numeric](24, 6) NULL,
	[ahf_paid_amt] [numeric](24, 6) NULL,
	[negot_savings_amt] [numeric](24, 6) NULL,
	[r_c_savings_amt] [numeric](24, 6) NULL,
	[cob_savings_amt] [numeric](24, 6) NULL,
	[src_cob_svngs_amt] [numeric](24, 6) NULL,
	[pri_payer_cvg_cd] [varchar](255) NULL,
	[cob_type_cd] [varchar](255) NULL,
	[cob_cd] [varchar](255) NULL,
	[prcdr_cd_ndc] [varchar](255) NULL,
	[member_cumbID] [varchar](255) NULL,
	[clm_ln_status_cd] [varchar](255) NULL,
	[src_member_id] [varchar](255) NULL,
	[reversal_cd] [varchar](255) NULL,
	[admit_cnt] [varchar](255) NULL,
	[admin_savings_amt] [numeric](24, 6) NULL,
	[adj_prvdr_dsgnn_cd] [varchar](255) NULL,
	[aex_plan_dsgntn_cd] [varchar](255) NULL,
	[benefit_tier_cd] [varchar](255) NULL,
	[aex_prvdr_spctg_cd] [varchar](255) NULL,
	[prod_distnctn_cd] [varchar](255) NULL,
	[billed_eligible_amt] [numeric](24, 6) NULL,
	[SPCLTY_CTG_CLS_CD] [varchar](255) NULL,
	[column128] [varchar](255) NULL,
	[column129] [varchar](255) NULL,
	[column130] [varchar](255) NULL,
	[pricing_mthd_cd] [varchar](255) NULL,
	[type_class_cd] [varchar](255) NULL,
	[specialty_ctg_cd] [varchar](255) NULL,
	[ttl_ded_met_ind] [varchar](255) NULL,
	[ttl_interest_amt] [numeric](24, 6) NULL,
	[ttl_surcharge_amt] [numeric](24, 6) NULL,
	[SRV_SPCLTY_CTG_CD] [varchar](255) NULL,
	[HCFA_PLC_SRV_CD] [varchar](255) NULL,
	[HCFA_ADMIT_SRC_CD] [varchar](255) NULL,
	[HCFA_ADMIT_TYPE_CD] [varchar](255) NULL,
	[SRC_ADMIT_DT] [varchar](255) NULL,
	[SRC_DISCHARGE_DT] [varchar](255) NULL,
	[prcdr_modifier_cd_2] [varchar](255) NULL,
	[prcdr_modifier_cd_3] [varchar](255) NULL,
	[ahf_det_order_cd] [varchar](255) NULL,
	[ahf_mbr_coins_amt] [numeric](24, 6) NULL,
	[ahf_mbr_copay_amt] [numeric](24, 6) NULL,
	[ahf_mbr_ded_amt] [numeric](24, 6) NULL,
	[sensitivity_ind] [varchar](255) NULL,
	[admit_type_cd] [varchar](255) NULL,
	[ORG_CD] [varchar](255) NULL,
	[carrier_ind] [varchar](5) NOT NULL,
	[LoadFileName] [varchar] (255) NULL,
	[Created_Date] [datetime] NULL,
	[Created_By] nvarchar(255) NULL,
	[Updated_Date] [datetime] NULL,
	[Updated_By] varchar(255) NULL
) ON [PRIMARY]  
GO


