USE [AetnaClaims_DEV]
GO

/****** Object:  Table [fact].[MemberEligibility]    Script Date: 9/16/2025 2:36:33 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[fact].[MemberEligibility]') AND type in (N'U'))
DROP TABLE [fact].[MemberEligibility]
GO

/****** Object:  Table [fact].[MemberEligibility]    Script Date: 9/16/2025 2:36:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [fact].[MemberEligibility](
	[member_id] [varchar](255) NULL,
	[eff_mm] [varchar](10) NULL,
	[msk_prefix_nm] [varchar](255) NULL,
	[last_nm] [varchar](255) NULL,
	[first_nm] [varchar](255) NULL,
	[suffix_nm] [varchar](255) NULL,
	[mbr_gender_cd] [varchar](255) NULL,
	[birth_dt] [varchar](10) NULL,
	[address_line_1_txt] [varchar](255) NULL,
	[address_line_2_txt] [varchar](255) NULL,
	[city_nm] [varchar](255) NULL,
	[state_postal_cd] [varchar](255) NULL,
	[county_cd] [varchar](255) NULL,
	[zip_cd] [varchar](255) NULL,
	[phone_number] [varchar](255) NULL,
	[src_member_id] [varchar](255) NULL,
	[mbr_rtp_type_cd] [varchar](255) NULL,
	[ssn_nbr] [varchar](255) NULL,
	[ps_unique_id] [varchar](255) NULL,
	[customer_nbr] [varchar](255) NULL,
	[group_nbr] [varchar](255) NULL,
	[subgroup_nbr] [varchar](255) NULL,
	[account_nbr] [varchar](255) NULL,
	[last_nm2] [varchar](255) NULL,
	[first_nm2] [varchar](255) NULL,
	[gender_cd] [varchar](255) NULL,
	[subscriber_brth_dt] [varchar](10) NULL,
	[subs_zip_cd] [varchar](255) NULL,
	[subs_st_postal_cd] [varchar](255) NULL,
	[county_cd2] [varchar](255) NULL,
	[SSN_NBR2] [varchar](255) NULL,
	[file_id] [varchar](255) NULL,
	[plsp_prod_cd] [varchar](255) NULL,
	[product_ln_cd] [varchar](255) NULL,
	[fund_ctg_cd] [varchar](255) NULL,
	[coverage_type_cd] [varchar](255) NULL,
	[ntwk_srv_area_id] [varchar](255) NULL,
	[cust_subseg_cd] [varchar](255) NULL,
	[medical_ind] [varchar](255) NULL,
	[drug_ind] [varchar](255) NULL,
	[sbstnc_abuse_ind] [varchar](255) NULL,
	[mental_health_ind] [varchar](255) NULL,
	[orig_covg_eff_dt] [varchar](10) NULL,
	[tax_id_nbr] [varchar](255) NULL,
	[pcp_prvdr_id] [varchar](255) NULL,
	[print_nm] [varchar](255) NULL,
	[address_line_1_txt2] [varchar](255) NULL,
	[address_line_2_txt2] [varchar](255) NULL,
	[city_nm2] [varchar](255) NULL,
	[state_postal_cd2] [varchar](255) NULL,
	[zip_cd2] [varchar](255) NULL,
	[npi_nbr] [varchar](255) NULL,
	[SPECIALTY_CTG_CD] [varchar](255) NULL,
	[org_id] [varchar](255) NULL,
	[first_vst_dt] [varchar](10) NULL,
	[last_vst_dt] [varchar](10) NULL,
	[visit_nbr] [varchar](255) NULL,
	[tax_id_nbr2] [varchar](255) NULL,
	[attr_prvdr_id] [varchar](255) NULL,
	[print_nm2] [varchar](255) NULL,
	[address_line_1_txt3] [varchar](255) NULL,
	[address_line_2_txt3] [varchar](255) NULL,
	[city_nm3] [varchar](255) NULL,
	[state_postal_cd3] [varchar](255) NULL,
	[zip_cd3] [varchar](255) NULL,
	[npi_nbr2] [varchar](255) NULL,
	[SPECIALTY_CTG_CD2] [varchar](255) NULL,
	[STATUS_IND] [varchar](255) NULL,
	[eff_dt] [varchar](10) NULL,
	[cncl_dt] [varchar](10) NULL,
	[SRC_CUMB_ID] [varchar](255) NULL,
	[SRC_CUMB_ID2] [varchar](255) NULL,
	[middle_nm] [varchar](255) NULL,
	[individual_id] [varchar](255) NULL,
	[pulse_fsi_score] [varchar](255) NULL,
	[ERG_Prospective_Score] [varchar](255) NULL,
	[ERG_Retro_Score] [varchar](255) NULL,
	[product_ln_cd2] [varchar](255) NULL,
	[aetna_card_number] [varchar](255) NULL,
	[grp_cntl_name] [varchar](255) NULL,
	[currect_record_indicator] [varchar](255) NULL,
	[cumb_id_seq_no] [varchar](255) NULL,
	[filler] [varchar](255) NULL,
	[derived] [varchar](255) NULL,
	[attprv_USE_SOURCE] [varchar](255) NULL,
	[ia_fncl_risk_cd] [varchar](255) NULL,
	[ORG_ID2] [varchar](255) NULL,
	[PLAN_ID] [varchar](255) NULL,
	[carrier_ind] [varchar](255) NULL,
	[LoadFile] [varchar](255) NOT NULL,
	[Created_Date] [datetime] NOT NULL,
	[CreatedBy] [varchar](34) NOT NULL,
	[Updated_Date] [datetime] NOT NULL,
	[Updated_By] [varchar](34) NOT NULL
) ON [PRIMARY]
GO


