USE [JCROYLE]
GO

/****** Object:  Table [Aetna].[MemberClaims]    Script Date: 8/15/2025 1:37:48 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Aetna].[MemberClaims]') AND type in (N'U'))
DROP TABLE [Aetna].[MemberClaims]
GO

/****** Object:  Table [Aetna].[MemberClaims]    Script Date: 8/15/2025 1:37:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Aetna].[MemberClaims](
	[ps_unique_id] [int]  NULL,
	[customer_nbr] [int] NULL,
	[group_nbr] [int] NULL,
	[idn_indicator] [nvarchar](50) NULL,
	[subgroup_nbr] [nvarchar](50) NULL,
	[account_nbr] [nvarchar](50) NULL,
	[file_id] [int] NULL,
	[clm_ln_type_cd] [nvarchar](50) NULL,
	[non_prfrrd_srv_cd] [nvarchar](50) NULL,
	[plsp_prod_cd] [nvarchar](50) NULL,
	[product_ln_cd] [nvarchar](50) NULL,
	[classification_cd] [nvarchar](50) NULL,
	[bnft_pkg_id] [nvarchar](50) NULL,
	[plan_id] [nvarchar](50) NULL,
	[non_prfrrd_srv_cd2] [nvarchar](50) NULL,
	[fund_ctg_cd] [nvarchar](50) NULL,
	[src_subscriber_id] [nvarchar](50) NULL,
	[emp_last_nm] [nvarchar](50) NULL,
	[emp_first_nm] [nvarchar](50) NULL,
	[emp_gender] [nvarchar](50) NULL,
	[subscriber_brth_dt] [nvarchar](50) NULL,
	[subs_zip_cd] [nvarchar](50) NULL,
	[subs_st_postal_cd] [nvarchar](50) NULL,
	[coverage_type_cd] [nvarchar](50) NULL,
	[ssn_nbr] [nvarchar](50) NULL,
	[member_id] [nvarchar](50) NOT NULL,
	[src_clm_mbr_id] [nvarchar](50) NULL,
	[mem_last_nm] [nvarchar](50) NULL,
	[mem_first_nm] [nvarchar](50) NULL,
	[mem_gender] [nvarchar](50) NULL,
	[mbr_rtp_type_cd] [nvarchar](50) NULL,
	[birth_dt] [nvarchar](50) NULL,
	[src_clm_id] [nvarchar](50) NULL,
	[src_claim_line_id] [nvarchar](50) NULL,
	[prev_clm_seg_id] [nvarchar](50) NULL,
	[derived_tcn_nbr] [float] NULL,
	[src_claim_line_id2] [nvarchar](50) NULL,
	[claim_line_id] [float] NOT NULL,
	[ntwk_srv_area_id] [int] NULL,
	[paid_prvdr_nsa_id] [nvarchar](50) NULL,
	[srv_capacity_cd] [nvarchar](50) NULL,
	[tax_id_format_cd] [nvarchar](50) NULL,
	[tax_id_nbr] [int] NULL,
	[print_nm] [nvarchar](50) NULL,
	[tax_id_format_cd2] [nvarchar](50) NULL,
	[tax_id_nbr2] [nvarchar](50) NULL,
	[srv_prvdr_id] [nvarchar](50) NULL,
	[print_nm2] [nvarchar](50) NULL,
	[address_line_1_txt] [nvarchar](50) NULL,
	[address_line_2_txt] [nvarchar](50) NULL,
	[city_nm] [nvarchar](50) NULL,
	[state_postal_cd] [nvarchar](50) NULL,
	[zip_cd] [nvarchar](50) NULL,
	[provider_type_cd] [nvarchar](50) NULL,
	[specialty_cd] [nvarchar](50) NULL,
	[payee_cd] [nvarchar](50) NULL,
	[paid_prvdr_par_cd] [nvarchar](50) NULL,
	[received_dt][nvarchar](50) NULL ,
	[adjn_dt] [nvarchar](50) NULL,
	[srv_start_dt] [nvarchar](50) NULL,
	[srv_stop_dt] [nvarchar](50) NULL,
	[paid_dt] [nvarchar](50) NULL,
	[FILLER] [nvarchar](50) NULL,
	[FILLER2] [nvarchar](50) NULL,
	[FILLER3] [nvarchar](50) NULL,
	[mdc_cd] [nvarchar](50) NULL,
	[drg_cd] [nvarchar](50) NULL,
	[prcdr_cd] [nvarchar](50) NULL,
	[prcdr_modifier_cd_1] [nvarchar](50) NULL,
	[prcdr_type_cd] [nvarchar](50) NULL,
	[ICD10_Indicator] [nvarchar](50) NULL,
	[MED_COST_SUBCTG_CD] [nvarchar](50) NULL,
	[prcdr_group_nbr] [nvarchar](50) NULL,
	[type_srv_cd] [nvarchar](50) NULL,
	[srv_benefit_cd] [nvarchar](50) NULL,
	[tooth_1_nbr] [nvarchar](50) NULL,
	[plc_srv_cd] [nvarchar](50) NULL,
	[dschrg_status_cd] [nvarchar](50) NULL,
	[revenue_cd] [nvarchar](50) NULL,
	[hcfa_bill_type_cd] [nvarchar](50) NULL,
	[unit_cnt] [nvarchar](50) NULL,
	[src_unit_cnt] [nvarchar](50) NULL,
	[src_billed_amt] [nvarchar](50) NULL,
	[billed_amt] [nvarchar](50) NULL,
	[not_covered_amt_1] [nvarchar](50) NULL,
	[not_covered_amt_2] [nvarchar](50) NULL,
	[not_covered_amt_3] [nvarchar](50) NULL,
	[clm_ln_msg_cd_1] [nvarchar](50) NULL,
	[clm_ln_msg_cd_2] [nvarchar](50) NULL,
	[clm_ln_msg_cd_3] [nvarchar](50) NULL,
	[covered_amt] [nvarchar](50) NULL,
	[allowed_amt] [nvarchar](50) NULL,
	[column93] [nvarchar](50) NULL,
	[srv_copay_amt] [nvarchar](50) NULL,
	[src_srv_copay_amt] [nvarchar](50) NULL,
	[deductible_amt] [nvarchar](50) NULL,
	[coinsurance_amt] [nvarchar](50) NULL,
	[src_coins_amt] [nvarchar](50) NULL,
	[bnft_payable_amt] [nvarchar](50) NULL,
	[paid_amt] [nvarchar](50) NULL,
	[cob_paid_amt] [nvarchar](50) NULL,
	[ahf_bfd_amt] [nvarchar](50) NULL,
	[ahf_paid_amt] [nvarchar](50) NULL,
	[negot_savings_amt] [nvarchar](50) NULL,
	[r_c_savings_amt] [nvarchar](50) NULL,
	[cob_savings_amt] [nvarchar](50) NULL,
	[src_cob_svngs_amt] [nvarchar](50) NULL,
	[pri_payer_cvg_cd] [nvarchar](50) NULL,
	[cob_type_cd] [nvarchar](50) NULL,
	[cob_cd] [nvarchar](50) NULL,
	[prcdr_cd_ndc] [nvarchar](50) NULL,
	[src_clm_mbr_id2] [nvarchar](50) NULL,
	[clm_ln_status_cd] [nvarchar](50) NULL,
	[src_member_id] [nvarchar](50) NULL,
	[reversal_cd] [nvarchar](50) NULL,
	[admit_cnt] [nvarchar](50) NULL,
	[admin_savings_amt] [nvarchar](50) NULL,
	[adj_prvdr_dsgnn_cd] [nvarchar](50) NULL,
	[aex_plan_dsgntn_cd] [nvarchar](50) NULL,
	[benefit_tier_cd] [nvarchar](50) NULL,
	[aex_prvdr_spctg_cd] [nvarchar](50) NULL,
	[prod_distnctn_cd] [nvarchar](50) NULL,
	[billed_eligible_amt] [nvarchar](50) NULL,
	[SPCLTY_CTG_CLS_CD] [nvarchar](50) NULL,
	[poa_cd_1] [nvarchar](50) NULL,
	[poa_cd_2] [nvarchar](50) NULL,
	[poa_cd_3] [nvarchar](50) NULL,
	[FILLER4] [nvarchar](50) NULL,
	[FILLER5] [nvarchar](50) NULL,
	[FILLER6] [nvarchar](50) NULL,
	[pricing_mthd_cd] [nvarchar](50) NULL,
	[type_class_cd] [nvarchar](50) NULL,
	[specialty_ctg_cd] [nvarchar](50) NULL,
	[srv_prvdr_npi] [nvarchar](50) NULL,
	[ttl_ded_met_ind] [nvarchar](50) NULL,
	[ttl_interest_amt] [nvarchar](50) NULL,
	[ttl_surcharge_amt] [nvarchar](50) NULL,
	[SRV_SPCLTY_CTG_CD] [nvarchar](50) NULL,
	[HCFA_PLC_SRV_CD] [nvarchar](50) NULL,
	[HCFA_ADMIT_SRC_CD] [nvarchar](50) NULL,
	[HCFA_ADMIT_TYPE_CD] [nvarchar](50) NULL,
	[SRC_ADMIT_DT] [nvarchar](50) NULL,
	[SRC_DISCHARGE_DT] [nvarchar](50) NULL,
	[prcdr_modifier_cd_2] [nvarchar](50) NULL,
	[prcdr_modifier_cd_3] [nvarchar](50) NULL,
	[poa_cd_4] [nvarchar](50) NULL,
	[poa_cd_5] [nvarchar](50) NULL,
	[poa_cd_6] [nvarchar](50) NULL,
	[poa_cd_7] [nvarchar](50) NULL,
	[poa_cd_8] [nvarchar](50) NULL,
	[poa_cd_9] [nvarchar](50) NULL,
	[poa_cd_10] [nvarchar](50) NULL,
	[pri_icd9_dx_cd] [nvarchar](50) NULL,
	[icd9_dx_cd_2] [nvarchar](50) NULL,
	[icd9_dx_cd_3] [nvarchar](50) NULL,
	[icd9_dx_cd_4] [nvarchar](50) NULL,
	[icd9_dx_cd_5] [nvarchar](50) NULL,
	[icd9_dx_cd_6] [nvarchar](50) NULL,
	[icd9_dx_cd_7] [nvarchar](50) NULL,
	[icd9_dx_cd_8] [nvarchar](50) NULL,
	[icd9_dx_cd_9] [nvarchar](50) NULL,
	[icd9_dx_cd_10] [nvarchar](50) NULL,
	[icd9_prcdr_cd_1] [nvarchar](50) NULL,
	[icd9_prcdr_cd_2] [nvarchar](50) NULL,
	[icd9_prcdr_cd_3] [nvarchar](50) NULL,
	[icd9_prcdr_cd_4] [nvarchar](50) NULL,
	[icd9_prcdr_cd_5] [nvarchar](50) NULL,
	[icd9_prcdr_cd_6] [nvarchar](50) NULL,
	[ahf_det_order_cd] [nvarchar](50) NULL,
	[ahf_mbr_coins_amt] [nvarchar](50) NULL,
	[ahf_mbr_copay_amt] [nvarchar](50) NULL,
	[ahf_mbr_ded_amt] [nvarchar](50) NULL,
	[sensitivity_indicator] [nvarchar](50) NULL,
	[hcfa_admit_type_cd2] [nvarchar](50) NULL,
	[ORG_CD] [nvarchar](50) NULL,


) ON [PRIMARY]
GO


